### ISSUE TITLE
Can't be lazy loaded with neobundle

### ISSUE THREAD

**Issue by jeaye** [rhysd/committia.vim#16]
I've created a neobundle ticket [here](https://github.com/Shougo/neobundle.vim/issues/434) with an example config showing that committia doesn't work/do anything if lazy loaded on filetype. Do you have any insight as to why this might be?

**Comment by rhysd** [comment]
That's because commitia.vim does not watch filetype to determine to open the commitia windows.  It watches `BufReadPost`.  Please see [plugin/commitia.vim](https://github.com/rhysd/committia.vim/blob/master/plugin/committia.vim) for more detail.

I don't recommend loading this plugin lazily because I carefully designed this plugin to load first.  `plugin/commitia.vim` has only 18 lines and can be loaded first.  You should measure the loading time at first with `--statuuptime` option, then determine loading the plugin lazily or not.  If you didn't measure yet, that's premature optimization.
