### ISSUE TITLE
Configure diff tool?

### ISSUE THREAD

**Issue by taylorthurlow** [rhysd/committia.vim#47]
I use [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) as my command line diff tool, configured with my `.gitconfig`. I'd like the ability to configure what program to call for generating diffs, if possible.

**Comment by rhysd** [comment]
committia.vim shows diff in Vim's edit buffer with `filetype=diff`. `diff-so-fancy` is not available since it's command line tool. I'm not sure but if there is a Vim plugin which provides the same functionality as `diff-so-fancy` in Vim, you would be able to enable it at `filetype=diff` and committia.vim will use it.
